# Generated by Django 3.2.19 on 2023-05-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='property_type',
            new_name='city',
        ),
    ]
