# Generated by Django 3.2.19 on 2023-05-31 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_property_type_amenity_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='date',
            new_name='dateEnd',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='bed_type',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='environment_type',
        ),
        migrations.AddField(
            model_name='amenity',
            name='bed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='amenity',
            name='rules',
            field=models.CharField(default='No rules', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='dateFrom',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
